### ISSUE TITLE
Consider exposing Github.Private?

### ISSUE THREAD

**Issue by hdgarrood** [jwiegley/github#102]
This would make it easier for consumers of this library to use api methods which are not yet implemented.

For example, I would like to be able to get a repo readme; looking at the code in #97, it would be very easy to do this if Github.Private were exposed. I suppose you might also want to add a note to the documentation saying "this is not considered part of the public api, use this at your own risk".

**Comment by mike-burns** [comment]
Or maybe there is a public function that could be written, exposed, and maintained - one which allows the user to do what you suggest: use API calls that are not yet wrapped.

**Comment by lally** [comment]
A wrapper around the GET/POST/PATCH apis would make this easier for us consumers.

**Comment by hdgarrood** [comment]
On second thoughts, I managed what I wanted to do by using `http-conduit` directly. It turned out to be really straightforward, so perhaps it makes more sense to let people do that when `github` doesn't have support for some API method? I'm not sure.

**Comment by jwiegley** [comment]
It's an exposed module now.
