### ISSUE TITLE
Updated package in Hackage

### ISSUE THREAD

**Issue by danpalmer** [jwiegley/github#118]
Would it be possible for a new release to be uploaded to Hackage? I'm trying to use some authenticated endpoints, but the current version on Hackage (0.13.2) doesn't support them yet.

Thanks!

**Comment by jwiegley** [comment]
There's still a test failure after the latest round of merges.  Would you be willing to help with it?

**Comment by phadej** [comment]
@jwiegley could you setup travis to see what fails. Current master seems to work on my machine with ghc-7.8.4 and ghc-.7.10.2 :tm:

**Comment by danpalmer** [comment]
@jwiegley I'd be up for looking at why the tests fail, however I'm new to this whole Haskell thing, so I may not get anywhere with it. Could be a good learning opportunity, could be a waste of my time and delay release. I'll see what I can do, but anyone else should feel free to take this on and do it.

@phadej I can look at adding Travis to this in the next few days perhaps?

**Comment by phadej** [comment]
the `.travis.yml` seems to be already in place, it's just not enabled for some reason.

**Comment by phadej** [comment]
I tried in my fork, the master is green: https://travis-ci.org/phadej/github/builds/80870030

**Comment by jwiegley** [comment]
Here's what I see, GHC 7.8.4:

```
Test suite github-test: RUNNING...

Github.Users
  userInfoFor
    returns information about the user FAILED [1]

Failures:

  spec/Github/UsersSpec.hs:15: (best-effort)
  1) Github.Users.userInfoFor returns information about the user
       uncaught exception: ErrorCall (Expected a Right and got a Left)

Source locations marked with "best-effort" are calculated heuristically and may be incorrect.

Randomized with seed 1374268446

Finished in 0.0007 seconds
1 example, 1 failure
Test suite github-test: FAIL
```

And with GHC 7.10:

```
Test suite github-test: RUNNING...

Github.Users
  userInfoFor
    returns information about the user FAILED [1]

Failures:

  spec/Github/UsersSpec.hs:15:
  1) Github.Users.userInfoFor returns information about the user
       uncaught exception: ErrorCall (Expected a Right and got a Left)

Randomized with seed 161638921

Finished in 0.0064 seconds
1 example, 1 failure
Test suite github-test: FAIL
```

Is it possible this is a Mac issue?

**Comment by phadej** [comment]
Those are `aeson-0.10.0.0` issues, https://github.com/jwiegley/github/issues/121. I'd recommend of having upper bounds on the dependencies.

**Comment by phadej** [comment]
@jwiegley this was closed, but the newest package on hackage is still 0.13.2

**Comment by jwiegley** [comment]
I still haven't put out a release because the tests don't pass for me.  But if they do pass for you, I'll push one anyway.

**Comment by phadej** [comment]
The tests fail sometimes, because the github rate limit is often used.

I changed the tests to print a bit more information, how they fail for you?
