### ISSUE TITLE
Split Definitions.hs

### ISSUE THREAD

**Issue by phadej** [jwiegley/github#119]
It's horribly long file, which compiles extremely long on GHC 7.10. Is it ok to split it. I'm sure that not all of the types form a single cycle.

**Comment by jwiegley** [comment]
I don't see any issue with that, do you?

**Comment by phadej** [comment]
This is very annoying if I want to add new functionality (and iterate during development). 
Alternatively I can add new types to new module,  so I don't need to recompile `Definitions` all the time. At that point, I'd prefer not to merge the new module into `Definitions` anymore.

**Comment by jwiegley** [comment]
I say split away then!
